# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4

  inputs:

    mavenPomFile: 'pom.xml'

    publishJUnitResults: false

    testResultsFiles: '**/surefire-reports/TEST-*.xml'

    javaHomeOption: 'JDKVersion'

    mavenVersionOption: 'Default'

    mavenAuthenticateFeed: false

    effectivePomSkip: false

    sonarQubeRunAnalysis: false

- task: JFrogMaven@1
  inputs:
        mavenPomFile: 'pom.xml'
        goals: 'install'
        artifactoryResolverService: 'azure'
        artifactoryDeployService: 'azure'
        targetDeployReleaseRepo: 'demo-class-libs-snapshot'
        targetDeploySnapshotRepo: 'demo-class-libs-snapshot'